### PR TITLE
Example of using front matter data to populate a template

### PR DESCRIPTION
**Pull request by sustanza**
I was thinking this might be a better way to design the templates so we can just populate the front matter versus filling out those templates. That way we can easily change up the post design templates. @poindexter12 What do you think? If you like I'll just update the rest of the posts... let me know.

### CODE REVIEW

**Review by poindexter12 — COMMENTED** [review]
can you do the others in here too? I like this better for sure

**Comment by sustanza** [comment]
Yeah that's the plan, I just wanted to run it by you first to see what you thought. This will be useful also if we maintain some database or excel sheet... easy programmatic generation of posts. I'll update the rest.

**Comment by sustanza** [comment]
@poindexter12 Updated all the posts as discussed. Please check over for errors as I've been coding for like 12+ hours and am kinda out of it haha

**Review by poindexter12 — APPROVED** [review]
👍

**Pull request merged**
